---
title: "Arithmetic Mean"
author: "Anthony A. Boyles"
date: "September 19, 2016"
---

```{r packages, message=FALSE}
library("MASS")
library("readr")
library("magrittr")
library("dplyr")
library("ShRoud")
library("randomForest")
library("e1071")
library("glmnet")
library("glmnetUtils")
```

## Plan

* Assemble the data!
* Model the data!
* Make Some Predictions!

## Assemble the Data!

```{r readData, message=FALSE}
rawtraining <- read_csv("deriveddata/training.csv")
rawtest <- read_csv("deriveddata/test.csv")
```

That was uneventful. Now, to make a preliminary preparation, let's partition the data into training and test sets for model building.

```{r dataPrep}
# There are a lot on NAs in the Data, which tend to gum things up. This is a handy function to slip into pipelines to 
temp <- rawtraining %>% mutate(train = runif(n()) < .7)
train <- temp %>% filter( train) %>% dplyr::select(-train)
test  <- temp %>% filter(!train) %>% dplyr::select(-train)
```

## Model the Data!

```{r LM}
modelLM <- stfu(stepAIC(lm(SalePrice ~ ., data=train)))

modelEN <- glmnet(SalePrice ~ ., data=train)

modelRF <- randomForest(SalePrice ~ ., data=factorize(train))

modelSVM <- svm(SalePrice ~ ., data=train)

prediction <- (
                predict(modelLM,           test,  type="response") +
  as.data.frame(predict(modelEN,           test,  type="response"))$s84 +
                predict(modelRF, factorize(test), type="response") +
                predict(modelSVM,          test,  type="response")
) / 4

model_output <- cbind(test, prediction)

rmse(log(model_output$SalePrice), log(model_output$prediction))
```

[Nice!](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/leaderboard)

## Make Some Predictions!

Let's rerun it on the entire Kaggle training set, predict on the test set, write and submit it.

```{r writeOut}
train <- rawtraining %>% select(-KitchenQual)
test  <- rawtest     %>% select(-KitchenQual)

modelLM  <- stfu(stepAIC(lm(SalePrice ~ ., data=train)))
modelEN  <- glmnet(SalePrice ~ ., data=train)
modelRF  <- randomForest(SalePrice ~ ., data=factorize(train))
modelSVM <- svm(SalePrice ~ ., data=train)

prediction <- (
                predict(modelLM,           test,  type="response")      +
  as.data.frame(predict(modelEN,           test,  type="response"))$s84 +
                predict(modelRF, factorize(test), type="response")      +
                predict(modelSVM,          test,  type="response")
) / 4

cbind(test, prediction) %>%
  dplyr::transmute(Id, SalePrice = prediction) %>%
  write_csv("predictions/predictionMean.csv")
```
